// Package proxy forwards OpenAI-compatible requests from the routed
// listener to local backends.
//
// Scope: this package delivers ONLY the forwarding handler. Route
// registration (POST /v1/chat/completions, /v1/completions, ...),
// GET /healthz, graceful shutdown and request logging belong to the
// server package, which wires this handler in:
//
//	mux.Handle("/v1/", proxy.NewHandlerFunc(store.Services, nodeID))
//
// # Service type ownership
//
// The canonical Service definition lives in internal/config. To avoid a
// duplicate concrete type, this package depends only on the narrow
// Service interface below. Any concrete type (including the future
// config.Service) satisfies it by implementing the five methods, or by
// wrapping with StaticService / a small adapter. No import of
// internal/config is needed here.
//
// # Behavior
//
//   - Route by exact match of request JSON "model" against ServedModels.
//   - Unknown/missing/unparseable model -> 400 JSON + X-Mooch-Node.
//   - Matched but unhealthy backend -> 503 JSON + X-Mooch-Node
//     (per team decision; proxy does not forward to unhealthy backends).
//   - Upstream URL = endpoint + apiBase + remaining path, query preserved.
//   - Hop-by-hop headers stripped; Content-Type/Accept/Authorization/
//     User-Agent (and all other end-to-end headers) pass through.
//   - Raw body forwarded unchanged via httputil.ReverseProxy with
//     FlushInterval -1 so SSE streams flow unbuffered.
//   - Upstream error status + body pass through untouched.
//   - Upstream unreachable -> 502 JSON + X-Mooch-Node.
package proxy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"strings"
	"time"
)

// NodeHeader is set on every error response generated by this package
// so central can tell which node rejected the request.
const NodeHeader = "X-Mooch-Node"

// MaxBodyBytes caps how much request body is buffered for model
// extraction. OpenAI chat requests are small; 16 MiB is generous and
// protects against OOM. Bodies larger than this are rejected with 413.
const MaxBodyBytes = 16 << 20

// Timeouts for the upstream transport. Dial/TLS/first-byte are bounded
// ("short upstream timeout for connect/read") but there is deliberately
// NO total request deadline, so an active SSE stream is never cut off.
const (
	dialTimeout           = 5 * time.Second
	tlsHandshakeTimeout   = 5 * time.Second
	responseHeaderTimeout = 30 * time.Second
	idleConnTimeout       = 90 * time.Second
	maxIdleConns          = 32
	maxIdleConnsPerHost   = 8
	streamFlushInterval   = -1 // flush SSE chunks immediately; see ReverseProxy docs
)

// Service is the narrow view of a backend this package needs. The
// canonical config.Service satisfies this interface by implementing
// these methods or via a thin adapter.
type Service interface {
	ServiceID() string
	BackendEndpoint() string // e.g. "http://127.0.0.1:8000"
	BackendAPIBase() string  // e.g. "/v1"
	ServedModels() []string
	BackendHealthy() bool
}

// StaticService is a plain struct implementing Service. Tests and early
// wiring use it directly; Person 1 may keep using it or replace it with
// config.Service + adapter.
type StaticService struct {
	ID       string
	Endpoint string
	APIBase  string
	Models   []string
	Healthy  bool
}

func (s StaticService) ServiceID() string       { return s.ID }
func (s StaticService) BackendEndpoint() string { return s.Endpoint }
func (s StaticService) BackendAPIBase() string  { return s.APIBase }
func (s StaticService) ServedModels() []string  { return s.Models }
func (s StaticService) BackendHealthy() bool    { return s.Healthy }

// Provider returns the current service snapshot. A func provider lets
// the server support SIGHUP config reload: pass a closure over the live
// config instead of a frozen slice.
type Provider func() []Service

// NewHandler serves forwarding for a static snapshot.
func NewHandler(services []Service, nodeID string) http.Handler {
	return NewHandlerFunc(func() []Service { return services }, nodeID)
}

// NewHandlerFunc serves forwarding with a dynamic provider.
// The handler logs with slog.Default until WithLogger sets a logger.
func NewHandlerFunc(provider Provider, nodeID string) http.Handler {
	if provider == nil {
		provider = func() []Service { return nil }
	}
	return &Handler{provider: provider, nodeID: nodeID, transport: defaultTransport(), logger: slog.Default()}
}

// Handler routes OpenAI-compatible requests to backends by model.
type Handler struct {
	provider  Provider
	nodeID    string
	transport *http.Transport
	logger    *slog.Logger
}

// WithLogger sets the structured logger. It returns the handler.
func (h *Handler) WithLogger(l *slog.Logger) *Handler {
	if l == nil {
		l = slog.Default()
	}
	h.logger = l
	return h
}

// log returns the active logger. It never returns nil.
func (h *Handler) log() *slog.Logger {
	if h.logger == nil {
		return slog.Default()
	}
	return h.logger
}

type modelRequest struct {
	Model string `json:"model"`
}

// openAIError mirrors the OpenAI error envelope so clients (OpenCode,
// SDKs) parse our 4xx/5xx responses.
type openAIError struct {
	Error struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    int    `json:"code,omitempty"`
	} `json:"error"`
}

func writeError(w http.ResponseWriter, nodeID string, status int, errType, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set(NodeHeader, nodeID)
	w.WriteHeader(status)
	var e openAIError
	e.Error.Message = msg
	e.Error.Type = errType
	e.Error.Code = status
	_ = json.NewEncoder(w).Encode(e)
}

// defaultTransport bounds connect/read without imposing a total deadline.
func defaultTransport() *http.Transport {
	return &http.Transport{
		Proxy: http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   dialTimeout,
			KeepAlive: 30 * time.Second,
		}).DialContext,
		TLSHandshakeTimeout:   tlsHandshakeTimeout,
		ResponseHeaderTimeout: responseHeaderTimeout,
		IdleConnTimeout:       idleConnTimeout,
		MaxIdleConns:          maxIdleConns,
		MaxIdleConnsPerHost:   maxIdleConnsPerHost,
		ForceAttemptHTTP2:     true,
	}
}

// findService returns the first service whose models contain model.
func findService(services []Service, model string) Service {
	for _, s := range services {
		if s == nil {
			continue
		}
		for _, m := range s.ServedModels() {
			if m == model {
				return s
			}
		}
	}
	return nil
}

// singleJoiningSlash joins URL path segments with exactly one slash,
// mirroring httputil.ReverseProxy's helper.
func singleJoiningSlash(a, b string) string {
	aslash := strings.HasSuffix(a, "/")
	bslash := strings.HasPrefix(b, "/")
	switch {
	case aslash && bslash:
		return a + b[1:]
	case !aslash && !bslash:
		return a + "/" + b
	}
	return a + b
}

// upstreamPath builds the upstream request path as
// endpoint.Path + apiBase + remaining, where remaining is the incoming
// path with a leading apiBase prefix stripped (to avoid /v1/v1/...).
func upstreamPath(endpointPath, apiBase, incomingPath string) string {
	if apiBase == "" {
		apiBase = "/"
	}
	// Normalise "/v1/" -> "/v1" so prefix stripping works.
	if len(apiBase) > 1 {
		apiBase = strings.TrimSuffix(apiBase, "/")
	}
	remaining := incomingPath
	if apiBase != "/" && (incomingPath == apiBase || strings.HasPrefix(incomingPath, apiBase+"/")) {
		remaining = strings.TrimPrefix(incomingPath, apiBase)
		if remaining == "" {
			remaining = "/"
		}
	}
	p := singleJoiningSlash(endpointPath, apiBase)
	p = singleJoiningSlash(p, remaining)
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	return p
}

// stripHopByHop removes hop-by-hop headers per RFC 9110 §7.6.1 (subset
// listed in REQUIREMENTS.md) plus any Proxy-* header. End-to-end
// headers (Content-Type, Accept, Authorization, User-Agent, ...) are
// left untouched for ReverseProxy to forward.
func stripHopByHop(h http.Header) {
	h.Del("Connection")
	h.Del("Keep-Alive")
	h.Del("Proxy-Authenticate")
	h.Del("Proxy-Authorization")
	h.Del("Te")
	h.Del("Trailer")
	h.Del("Transfer-Encoding")
	h.Del("Upgrade")
	for k := range h {
		if strings.HasPrefix(http.CanonicalHeaderKey(k), "Proxy-") {
			h.Del(k)
		}
	}
}

// ServeHTTP routes an incoming request to the backend serving its
// model and reverse-proxies it. It logs each decision with slog.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	logger := h.log()
	// 1. Buffer the body so we can inspect "model" and still forward the
	// raw bytes unchanged.
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, MaxBodyBytes))
	if err != nil {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", "",
			"status", http.StatusRequestEntityTooLarge,
		)
		writeError(w, h.nodeID, http.StatusRequestEntityTooLarge, "request_too_large",
			fmt.Sprintf("request body too large (limit %d bytes)", MaxBodyBytes))
		return
	}

	// 2. Extract model without altering the body.
	var mr modelRequest
	if len(bytes.TrimSpace(body)) == 0 {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", "",
			"status", http.StatusBadRequest,
		)
		writeError(w, h.nodeID, http.StatusBadRequest, "invalid_request_error",
			"missing request body: OpenAI requests require a JSON \"model\" field")
		return
	}
	dec := json.NewDecoder(bytes.NewReader(body))
	if err := dec.Decode(&mr); err != nil {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", "",
			"status", http.StatusBadRequest,
		)
		writeError(w, h.nodeID, http.StatusBadRequest, "invalid_request_error",
			"invalid JSON body: "+err.Error())
		return
	}
	if mr.Model == "" {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", "",
			"status", http.StatusBadRequest,
		)
		writeError(w, h.nodeID, http.StatusBadRequest, "invalid_request_error",
			"missing \"model\" in request body: no backend can be selected")
		return
	}

	// 3. Route by model.
	svc := findService(h.provider(), mr.Model)
	if svc == nil {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", mr.Model,
			"status", http.StatusBadRequest,
		)
		writeError(w, h.nodeID, http.StatusBadRequest, "model_not_found",
			fmt.Sprintf("unknown model %q: no configured service serves it", mr.Model))
		return
	}

	// 4. Reject unhealthy backends with 503 (team decision).
	if !svc.BackendHealthy() {
		logger.Warn("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", mr.Model,
			"status", http.StatusServiceUnavailable,
			"service", svc.ServiceID(),
		)
		writeError(w, h.nodeID, http.StatusServiceUnavailable, "service_unavailable",
			fmt.Sprintf("model %q is served by %q, which is currently unhealthy", mr.Model, svc.ServiceID()))
		return
	}

	// 5. Parse upstream endpoint.
	target, err := url.Parse(svc.BackendEndpoint())
	if err != nil || target.Scheme == "" || target.Host == "" {
		logger.Error("proxy reject",
			"component", "proxy",
			"node_id", h.nodeID,
			"method", r.Method,
			"path", r.URL.Path,
			"model", mr.Model,
			"status", http.StatusBadGateway,
			"service", svc.ServiceID(),
		)
		writeError(w, h.nodeID, http.StatusBadGateway, "bad_gateway",
			fmt.Sprintf("service %q has invalid endpoint %q", svc.ServiceID(), svc.BackendEndpoint()))
		return
	}

	apiBase := svc.BackendAPIBase()
	if apiBase == "" {
		apiBase = "/"
	}
	upPath := upstreamPath(target.Path, apiBase, r.URL.Path)
	query := r.URL.RawQuery // preserve query params

	proxy := &httputil.ReverseProxy{
		Transport:     h.transport,
		FlushInterval: streamFlushInterval, // stream SSE chunks unmodified
		Director: func(req *http.Request) {
			req.URL.Scheme = target.Scheme
			req.URL.Host = target.Host
			req.URL.Path = upPath
			req.URL.RawQuery = query
			// Preserve the incoming Host semantics for backends that
			// route on it? No: set Host to upstream host so vLLM/ollama
			// see what they expect.
			req.Host = target.Host
			stripHopByHop(req.Header)
		},
		ModifyResponse: func(resp *http.Response) error {
			// Passthrough: preserve upstream status + body (including
			// error JSON and text/event-stream) unmodified.
			stripHopByHop(resp.Header)
			return nil
		},
		ErrorHandler: func(w http.ResponseWriter, _ *http.Request, err error) {
			logger.Error("proxy upstream error",
				"component", "proxy",
				"node_id", h.nodeID,
				"method", r.Method,
				"path", r.URL.Path,
				"model", mr.Model,
				"status", http.StatusBadGateway,
				"service", svc.ServiceID(),
			)
			writeError(w, h.nodeID, http.StatusBadGateway, "bad_gateway",
				fmt.Sprintf("upstream %q unreachable: %v", svc.ServiceID(), err))
		},
	}

	// 6. Restore the raw body for the upstream request.
	r.Body = io.NopCloser(bytes.NewReader(body))
	r.ContentLength = int64(len(body))
	r.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(bytes.NewReader(body)), nil
	}

	// Log the route decision. The proxy writes the response directly.
	logger.Info("proxy forward",
		"component", "proxy",
		"node_id", h.nodeID,
		"method", r.Method,
		"path", r.URL.Path,
		"model", mr.Model,
		"service", svc.ServiceID(),
	)

	// Serve with the client context as-is: client disconnect still
	// cancels upstream, but no total deadline is imposed here so an
	// active SSE stream is never cut off by this package. Any server
	// timeouts belong to the server package.
	proxy.ServeHTTP(w, r)
}
